import { Inter } from "next/font/google";
import "./globals.css";
import Foter from "./componet/Foter";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Join Work",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='p-5'>
         <div className="sm:center md:center lg:center">
        
        {children}
      
        <Foter></Foter>
       
        </div>
        </body>
    </html>
  );
}
